name: Run Docker Script with Root Access

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-docker-script:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Download Docker.sh script
    - name: Download Docker.sh
      run: wget https://raw.githubusercontent.com/choir94/Airdropguide/refs/heads/main/Docker.sh

    # Step 2: Debug root access and run Docker.sh
    - name: Debug Root Access and Run Script
      run: |
        echo "Checking root access..."
        whoami
        id
        chmod +x Docker.sh
        sudo ./Docker.sh 6D6BEE80-B63D-47C4-9253-89015DA51A41
