name: Run Docker Script with Parameter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-docker-script:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Download and Run Docker.sh with Parameter
    - name: Download and Run Docker.sh
      run: |
        wget https://raw.githubusercontent.com/choir94/Airdropguide/refs/heads/main/Docker.sh
        chmod +x Docker.sh
        ./Docker.sh 6D6BEE80-B63D-47C4-9253-89015DA51A41
